In [10]:
import numpy as np
import pandas as pd

In [12]:
data = np.load("segment_01.npz")
print(data.files)
print(data["t"])

q_df = pd.DataFrame(data["q"])
t_df = pd.DataFrame(data["t"])

['t', 'q']
[1.16450787e-02 3.15878391e-02 5.15003204e-02 ... 1.11491847e+02
 1.11511762e+02 1.11531162e+02]

In [19]:
q_df

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.022554,0.003811,0.002301,0.883885,-0.001654,-0.002800,0.011816,-0.010606,-0.065877,0.900123,0.004123,-0.007217
1,0.022554,0.003811,0.002289,0.883885,-0.001678,-0.002792,0.011816,-0.010618,-0.065889,0.900123,0.004123,-0.007202
2,0.022554,0.003811,0.002301,0.883885,-0.001654,-0.002792,0.011804,-0.010606,-0.065889,0.900123,0.004123,-0.007194
3,0.022554,0.003823,0.002301,0.883885,-0.001654,-0.002792,0.011792,-0.010606,-0.065889,0.900123,0.004123,-0.007202
4,0.022554,0.003847,0.002289,0.883885,-0.001678,-0.002792,0.011804,-0.010606,-0.065913,0.900123,0.004147,-0.007202
...,...,...,...,...,...,...,...,...,...,...,...,...
5572,0.033760,0.083578,0.046571,1.119866,-0.069245,0.008575,0.060436,-0.038302,-0.299438,1.263269,0.016478,-0.079345
5573,0.033772,0.083578,0.046559,1.119866,-0.069269,0.008567,0.060412,-0.038326,-0.299438,1.263293,0.016466,-0.079345
5574,0.033772,0.083566,0.046559,1.119866,-0.069269,0.008575,0.060412,-0.038326,-0.299438,1.263281,0.016466,-0.079345
5575,0.033760,0.083590,0.046559,1.119866,-0.069257,0.008575,0.060412,-0.038326,-0.299426,1.263269,0.016466,-0.079353
5576,0.033772,0.083614,0.046559,1.119854,-0.069269,0.008567,0.060436,-0.038326,-0.299438,1.263281,0.016478,-0.079345

In [16]:
t_df

               0
0       0.011645
1       0.031588
2       0.051500
3       0.071536
4       0.091400
...          ...
5572  111.451186
5573  111.471578
5574  111.491847
5575  111.511762
5576  111.531162

[5577 rows x 1 columns]