In [7]:
import os
import os.path as osp
import numpy as np
import pandas as pd

In [27]:
class Config: pass
with open("/home/johng/repo/G1_deploy/deploy_real/configs/config_high_level.yaml", 'r') as f:
    import yaml
    f = yaml.safe_load(f)
    cfg = Config()
    for k, v in f.items():
        setattr(cfg, k, np.array(v) if isinstance(v, list) else v)
    print(cfg.action_joints)
    print(cfg.fixed_joints)
    print(type(cfg.fixed_joints))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28]
None
<class 'NoneType'>

In [30]:
file_dir = os.getcwd()
record_path = osp.join(file_dir,"deploy_real", "records", "single_2.npz")
print(record_path)
data = np.load(record_path)
print(data)
print(data['q'])

/home/johng/repo/G1_deploy/deploy_real/records/single_2.npz
NpzFile '/home/johng/repo/G1_deploy/deploy_real/records/single_2.npz' with keys: q
[ 0.0132458  -0.04946747 -0.0064415   0.23600294 -0.08476276 -0.00525161
  0.00312591  0.00712449  0.01253481  0.23357414 -0.07872018  0.011435
  0.06299548  0.          0.          0.0703474   0.06102367  0.13040036
  1.29453599 -0.22857513  0.13592604  0.10057545 -0.11103385 -0.04573181
 -1.47956049  0.26066887  0.09601761 -0.49082786 -0.00842156]

In [16]:
data = np.load(record_path)
print(data.files)
print(data["t"])

q_df = pd.DataFrame(data["q"])
t_df = pd.DataFrame(data["t"])

['t', 'q']
[4.62865829e-03 2.28240490e-02 4.27474976e-02 6.26974106e-02
 8.35144520e-02 1.02455378e-01 1.22657299e-01 1.42339468e-01
 1.62609100e-01 1.82616949e-01 2.02511072e-01 2.24363327e-01
 2.48085022e-01 2.62536526e-01 2.83160210e-01 3.02203417e-01
 3.22258711e-01 3.46159697e-01 3.65889549e-01 3.83054256e-01
 4.02063847e-01 4.21981573e-01 4.44436550e-01 4.63781834e-01
 4.83245373e-01 5.03752470e-01 5.22921562e-01 5.48864603e-01
 5.65165043e-01 5.83748102e-01 6.03294134e-01 6.26499653e-01
 6.42688274e-01 6.62308455e-01 6.84199333e-01 7.02477217e-01
 7.22977400e-01 7.44503498e-01 7.62576103e-01 7.82017946e-01
 8.03263903e-01 8.21907282e-01 8.42762470e-01 8.64034653e-01
 8.88002157e-01 9.02491570e-01 9.22855854e-01 9.43045616e-01
 9.63199615e-01 9.84373331e-01 1.00357056e+00 1.02239966e+00
 1.04228759e+00 1.06264687e+00 1.08583236e+00 1.10221863e+00
 1.12280416e+00 1.14729786e+00 1.16315317e+00 1.18341303e+00
 1.20193267e+00 1.22368813e+00 1.24271345e+00 1.26237965e+00
 1.28481650e+00 1.30249166e+00 1.32263398e+00 1.34820366e+00
 1.36246991e+00 1.38674784e+00 1.40220404e+00 1.42289472e+00
 1.44218063e+00 1.46349216e+00 1.48385811e+00 1.50167799e+00
 1.52201700e+00 1.54242778e+00 1.56290364e+00 1.58367372e+00
 1.60294461e+00 1.62230849e+00 1.64410448e+00 1.66382480e+00
 1.68309379e+00 1.70241189e+00 1.72242308e+00 1.74212503e+00
 1.76234889e+00 1.78236032e+00 1.80229282e+00 1.82401562e+00
 1.84446287e+00 1.86326218e+00 1.88732433e+00 1.90256381e+00
 1.92207646e+00 1.94228458e+00 1.96250725e+00 1.98254061e+00
 2.00278330e+00 2.02271891e+00 2.04318404e+00 2.06267095e+00
 2.08672690e+00 2.10256553e+00 2.12242174e+00 2.14228082e+00
 2.16322398e+00 2.18266821e+00 2.20431900e+00 2.22436070e+00
 2.24273825e+00 2.26266718e+00 2.28529549e+00 2.30319810e+00
 2.32266045e+00 2.34210563e+00 2.36295033e+00 2.38323665e+00
 2.40361905e+00 2.42257905e+00 2.44263363e+00 2.46390963e+00
 2.48327732e+00 2.50336242e+00 2.52509713e+00 2.54211450e+00
 2.56295705e+00 2.58208346e+00 2.60229373e+00 2.62300849e+00
 2.64628482e+00 2.66217971e+00 2.68229294e+00 2.70396066e+00
 2.72256064e+00 2.74243140e+00 2.76346231e+00 2.78368998e+00
 2.80390668e+00 2.82353878e+00 2.84349394e+00 2.86232328e+00
 2.88297749e+00 2.90311289e+00 2.92221165e+00 2.94221854e+00
 2.96212053e+00 2.98241806e+00 3.00223351e+00 3.02297425e+00
 3.04219842e+00 3.06212330e+00 3.08777499e+00 3.10296273e+00
 3.12251210e+00 3.14705157e+00 3.16268826e+00 3.18275142e+00
 3.20254087e+00 3.22237301e+00 3.24246168e+00 3.26238632e+00
 3.28482342e+00 3.30465436e+00 3.32312179e+00 3.34226537e+00
 3.36258245e+00 3.38239336e+00 3.40286326e+00 3.42777538e+00
 3.44292879e+00 3.46294594e+00 3.48243284e+00 3.50259924e+00
 3.52336478e+00 3.55082798e+00 3.56363225e+00 3.58417177e+00
 3.60205173e+00 3.62281656e+00 3.64185429e+00 3.66287017e+00
 3.68512082e+00 3.70415926e+00 3.72359037e+00 3.74293518e+00
 3.76194382e+00 3.78219032e+00 3.80272698e+00 3.82261968e+00
 3.84272718e+00 3.86412883e+00 3.88295150e+00 3.90267754e+00
 3.92262602e+00 3.94242358e+00 3.96256471e+00 3.98365140e+00
 4.00398397e+00 4.02266335e+00 4.04183221e+00 4.06215119e+00
 4.08214545e+00 4.10202432e+00 4.12213373e+00 4.14263582e+00
 4.16201758e+00 4.18265319e+00 4.20208907e+00 4.22358799e+00
 4.24257374e+00 4.26253319e+00 4.28263879e+00 4.30247140e+00
 4.32570863e+00 4.34286833e+00 4.36237860e+00 4.38215375e+00
 4.40249920e+00 4.42251873e+00 4.44205570e+00 4.46206474e+00
 4.48269320e+00 4.50202990e+00 4.52423072e+00 4.54866338e+00
 4.56207490e+00 4.58258319e+00 4.60197973e+00 4.62295794e+00
 4.64252639e+00 4.66251564e+00 4.68193841e+00 4.70319557e+00
 4.72458220e+00 4.74600983e+00 4.76229596e+00 4.78262019e+00
 4.80210757e+00 4.82369447e+00 4.84274983e+00 4.86212564e+00
 4.88330603e+00 4.90244842e+00 4.92207265e+00 4.94315290e+00
 4.96254134e+00 4.98334002e+00 5.00292325e+00 5.02248120e+00
 5.04405379e+00 5.06249595e+00 5.08344626e+00 5.10301161e+00
 5.12304997e+00 5.14472723e+00 5.16291261e+00 5.18315172e+00
 5.20292687e+00 5.22318816e+00 5.24266481e+00 5.26272392e+00
 5.28366780e+00 5.30205011e+00 5.32263923e+00 5.34752345e+00
 5.36201382e+00 5.38242817e+00 5.40233040e+00 5.42337322e+00
 5.44255924e+00 5.46251488e+00 5.48216105e+00 5.50250506e+00
 5.52229285e+00 5.54204631e+00 5.56203818e+00 5.58335376e+00
 5.60267282e+00 5.62197661e+00 5.64217758e+00 5.66230083e+00
 5.68366098e+00 5.70198417e+00 5.72204471e+00 5.74717951e+00
 5.76257181e+00 5.78260493e+00 5.80253434e+00 5.82231498e+00
 5.84362698e+00 5.86257076e+00 5.88306141e+00 5.90324235e+00
 5.92243719e+00 5.94235778e+00 5.96220613e+00 5.98285937e+00
 6.00344920e+00 6.02293396e+00 6.04220867e+00 6.06231022e+00
 6.08230662e+00 6.10260344e+00 6.12262654e+00 6.14775205e+00
 6.16765332e+00 6.18272519e+00 6.20248485e+00 6.22229290e+00
 6.24260163e+00 6.26332641e+00 6.28455114e+00 6.30377054e+00
 6.32318854e+00 6.34694052e+00 6.36295319e+00 6.38302279e+00
 6.40253305e+00 6.42566609e+00 6.44500422e+00 6.46249533e+00
 6.48295188e+00 6.50261712e+00 6.52282786e+00 6.54475808e+00
 6.56274104e+00 6.58257151e+00]

In [17]:
print(len(data['t']))
print(data['q'][-1])

330
[ 0.05141233 -0.04444949  0.09703627 -0.10206965 -0.30427948  0.04825904
  0.16679645 -0.06443918 -0.30093589  1.06709933  0.28823259 -0.06824681]

In [19]:
q_df

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.082092,0.051041,0.365878,1.412796,-0.294632,-0.035343,0.169265,-0.064990,-0.301008,1.066236,0.288293,-0.063238
1,0.082104,0.051053,0.365890,1.412748,-0.294632,-0.035343,0.169265,-0.064966,-0.301020,1.066225,0.288293,-0.063238
2,0.082104,0.051077,0.365878,1.412676,-0.294620,-0.035351,0.169277,-0.064978,-0.301044,1.066236,0.288316,-0.063254
3,0.082128,0.051065,0.365902,1.412641,-0.294644,-0.035351,0.169289,-0.064966,-0.301020,1.066249,0.288316,-0.063238
4,0.082104,0.051077,0.365878,1.412641,-0.294632,-0.035343,0.169301,-0.064966,-0.301020,1.066236,0.288316,-0.063238
...,...,...,...,...,...,...,...,...,...,...,...,...
325,0.051388,-0.043754,0.098990,-0.102094,-0.304256,0.048267,0.166796,-0.064439,-0.300912,1.067087,0.288233,-0.068247
326,0.051400,-0.044402,0.098498,-0.102082,-0.304267,0.048259,0.166796,-0.064439,-0.300912,1.067111,0.288233,-0.068247
327,0.051412,-0.044581,0.097863,-0.102070,-0.304244,0.048267,0.166796,-0.064439,-0.300912,1.067099,0.288233,-0.068247
328,0.051412,-0.044497,0.097300,-0.102094,-0.304256,0.048267,0.166796,-0.064439,-0.300912,1.067099,0.288233,-0.068247
329,0.051412,-0.044449,0.097036,-0.102070,-0.304279,0.048259,0.166796,-0.064439,-0.300936,1.067099,0.288233,-0.068247

In [18]:
t_df

            0
0    0.004629
1    0.022824
2    0.042747
3    0.062697
4    0.083514
..        ...
325  6.502617
326  6.522828
327  6.544758
328  6.562741
329  6.582572

[330 rows x 1 columns]